.gitignore, incoming.txt, incoming.yaml, kg_emerging_viruses/transform/example_transform/example_transform_script.py, run.py
Redo workflow per convo with N2V team Mar 20
=> Redo workflow for transform

.gitignore
The `download.yaml` has hard-coded requirements for `data/raw` and `data/transformed` directories. This commit:  
- Adds these folders with `.gitkeep`.   
- Modifies `.gitignore` to ensure that all data or added files will be ignored from these directories.
=> adding required directories

.travis.yml, kg_emerging_viruses/download.py, kg_emerging_viruses/transform.py, kg_emerging_viruses/transform_utils/drug_central/__init__.py, kg_emerging_viruses/transform_utils/drug_central/drug_central.py, kg_emerging_viruses/transform_utils/example_transform/example_transform_script.py, kg_emerging_viruses/transform_utils/zhou_host_proteins/zhou_transform.py, kg_emerging_viruses/utils/download_utils.py, kg_emerging_viruses/utils/transform_utils.py, run.py, setup.py, tests/test_run.py, tests/test_version.py
- Enforces Google Style Guides and adds typing   
- Adding install of `mypy` and `pylint`
- Adding `pylint` and `mypy` calls to `Travis.yml`  
_`#TODO: typing is not completely strict and can be further refined in the `transform_utils.py` script`_
<br>
Closes #26
=> Reformatting scripts

download.yaml, kg_emerging_viruses/transform.py, kg_emerging_viruses/transform_utils/string_ppi/__init__.py, kg_emerging_viruses/transform_utils/string_ppi/string_ppi.py, requirements.txt, setup.py
Related to #10 
This is a first pass.
Will add another PR with some improvements.
=> Transform for STRING data source

run.py, tests/test_run.py
Changed tests of `run.py` to fix timeout
=> Fix unit test timeout

kg_emerging_viruses/transform.py, kg_emerging_viruses/transform_utils/string_ppi/string_ppi.py
=> Add more information to nodes and edges for STRING ingest

download.yaml, kg_covid_19/transform_utils/drug_central/drug_central.py, kg_covid_19/utils/transform_utils.py
- fix download of Drug Central file - somehow broken during the last few merges
- also added Exception type for when item is not found in a dict
=> Fix failure to download Drug Central files

kg_covid_19/transform.py, kg_covid_19/transform_utils/transform.py, kg_covid_19/transform_utils/zhou_host_proteins/__init__.py, kg_covid_19/transform_utils/zhou_host_proteins/zhou_transform.py, tests/test_transform_class.py
Refactor Zhou ingest so it looks like the others
=> Standardize zhou ingest

README.rst
also added some words to project description
=> Update README to include load command

download.yaml, kg_covid_19/transform.py, kg_covid_19/transform_utils/__init__.py, kg_covid_19/transform_utils/example_transform/example_transform_script.py, kg_covid_19/transform_utils/hpo/__init__.py, kg_covid_19/transform_utils/hpo/hpo.py, kg_covid_19/transform_utils/zhou_host_proteins/__init__.py, kg_covid_19/utils/transform_utils.py, sample-merge-config.yml, setup.py
=> Add hpo ingest

merge.yaml
I neglected make an entry for pharmgkb in merge.yaml
=> Add entry in merge.yaml for pharmgkb, and alphabetize entries

download.yaml
=> Update hpo.obo to purl.obolibrary.org/obo/hp.obo

download.yaml, kg_covid_19/transform.py, kg_covid_19/transform_utils/example_transform/example_transform_script.py, kg_covid_19/transform_utils/sars_cov_2_gene_annot/__init__.py, kg_covid_19/transform_utils/sars_cov_2_gene_annot/sars_cov_2_gene_annot.py, kg_covid_19/utils/transform_utils.py, merge.yaml, tests/resources/uniprot_sars-cov-2_SNIPPET.gpa, tests/resources/uniprot_sars-cov-2_SNIPPET.gpi, tests/test_sars_cov_2_gene_annot.py
GO annotations for each SARS-CoV-2 gene
Closes #19
=> SARS-CoV-2 gene annotations

download.yaml, kg_covid_19/transform_utils/scibite_cord/scibite_cord.py
The transform runs properly now
=> Fix URL for SciBite CORD-19 annotated dataset

merge.yaml
=> Remove cord from merge.yaml (for now)

requirements.txt
where @deepakunni3's improved code is located
=> Update KGX in requirements.txt to point to NCATS repo

kg_covid_19/load_utils/merge_kg.py, kg_covid_19/transform_utils/scibite_cord/scibite_cord.py
@justaddcoffee This fixes the merge script.
It also fixes a small bug in SciBite-CORD Transform.
Thought I'll bundle it as part of this PR.
=> Fix merge script

download.yaml, kg_covid_19/transform.py, kg_covid_19/transform_utils/drug_central/drug_central.py, kg_covid_19/transform_utils/example_transform/example_transform_script.py, kg_covid_19/transform_utils/hpo/hpo.py, kg_covid_19/transform_utils/ontology/__init__.py, kg_covid_19/transform_utils/ontology/ontology_transform.py, kg_covid_19/transform_utils/pharmgkb/pharmgkb.py, kg_covid_19/transform_utils/sars_cov_2_gene_annot/sars_cov_2_gene_annot.py, kg_covid_19/transform_utils/scibite_cord/scibite_cord.py, kg_covid_19/transform_utils/string_ppi/string_ppi.py, kg_covid_19/transform_utils/transform.py, kg_covid_19/transform_utils/ttd/ttd.py, kg_covid_19/transform_utils/zhou_host_proteins/zhou_transform.py, merge.yaml
This PR adds an OntologyTransform that takes care of parsing Ontologies (as JSON format).
It uses KGX under the hood to do the transformation and export TSV.
This PR handles ingests for GO, HP and Mondo.
Addresses #97 and #72
=> Ontology ingest

merge.yaml
=> Remove stray - character in merge.yaml

.travis.yml, download.yaml, merge.yaml
- add yamllint to travis
- fix yamllint errors in `download.yaml` or `merge.yaml`
=> Add yamllint to travis check

requirements.txt
to possibly fix ntriples output
=> Updated kgx requirement in requirements.txt

kg_covid_19/transform_utils/string_ppi/string_ppi.py
=> Add CURIE prefix ENSEMBL to ensembl proteins

kg_covid_19/transform_utils/ttd/ttd.py
=> Fix data error - use drug CURIE instead of target CURIE

kg_covid_19/query.py, kg_covid_19/query_utils/query.py, kg_covid_19/query_utils/target_candidates.py, kg_covid_19/query_utils/target_candidates/target_candidates.py, kg_covid_19/transform_utils/intact/intact.py, run.py, tests/resources/P0DTC1.edges.tsv, tests/resources/P0DTC1.nodes.tsv, tests/resources/sars_cov_2_gene_annot_SNIPPET.tsv, tests/resources/test_sars_cov2_intact_nodes.tsv, tests/test_intact.py, tests/test_sars_cov2_pro_candidates_nodes_SNIPPET.tsv, tests/test_targetCandidates.py
- another run.py step, 'query' along with download/transform/load
- added a query to output candidate COVID19 drug targets, to iterate on:
`python run.py query -q TargetCandidates`
writes out:
`data/queries/target_candidates.tsv`
=> Add query command

Jenkinsfile
=> Remove gitkeep file before uploading transformed files, fix logic error in transform stage 

Jenkinsfile
- fix bug - pigz nt after generating journal
- give blazegraph-runner more memory
=> Minor fixes/improvements to Jenkinsfile

Jenkinsfile
=> Up memory while running blazegraph-runner

Jenkinsfile
=> Fix path to blazegraph-runner in Jenkins

download.yaml, kg_covid_19/query_utils/target_candidates/target_candidates.py, kg_covid_19/utils/download_utils.py
- update intact source URL to a better link
- a bit of logging while downloading to make it more clear what file is failing to download in case of a problem
- tweaking of query to generate target list - remove redundant entries
=> Update intact ingest source file

Jenkinsfile, merge.yaml
=> Remove rdf conversion stage

Jenkinsfile
Wrong path to nt file in blazegraph journal stage
=> Fix path to nt file

download.yaml, kg_covid_19/transform_utils/scibite_cord/scibite_cord.py
- Simplify modeling of cooccurrences in SciBiteTransform
- Parses country codes to CURIEs from Wikidata
=> Simplify modeling cooccurrences in SciBite Transform

kg_covid_19/transform_utils/string_ppi/string_ppi.py
=> Fix empty nodes.tsv in STRING transform

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/dataset-request.md
- Updated dataset request template per Chris's suggestions
- Added a bug report issue template
=> Update issue templates

kg_covid_19/transform_utils/scibite_cord/scibite_cord.py
=> Fix bug with repeating edges when parsing co-occurrence data from SciBite

kg_covid_19/transform_utils/intact/intact.py
=> Correctly type drugs and nucleic acids in IntAct ingest

kg_covid_19/transform_utils/drug_central/drug_central.py, kg_covid_19/transform_utils/intact/intact.py, kg_covid_19/transform_utils/ontology/ontology_transform.py, kg_covid_19/transform_utils/pharmgkb/pharmgkb.py, kg_covid_19/transform_utils/sars_cov_2_gene_annot/sars_cov_2_gene_annot.py, kg_covid_19/transform_utils/scibite_cord/scibite_cord.py, kg_covid_19/transform_utils/string_ppi/node_header.json, kg_covid_19/transform_utils/string_ppi/string_ppi.py, kg_covid_19/transform_utils/ttd/ttd.py, kg_covid_19/transform_utils/zhou_host_proteins/zhou_transform.py, tests/test_intact.py, tests/test_sars_cov_2_gene_annot.py
Every source now emits `provided_by` property for both nodes and edges.
=> Add provided_by to nodes

kg_covid_19/transform_utils/ttd/ttd.py
=> Fix TTD curie prefix

README.rst, setup.py
=> Put python3.7 requirement in setup.py

kg_covid_19/transform_utils/string_ppi/string_ppi.py
To address #235 - I was erroneously writing the Uniprot CURIE prefix as UniprotKB instead of UniProtKB
=> Fix UniProtKB CURIE prefix in STRING

Jenkinsfile, tests/test_string.py
Change transform step to remove download of transformed files on failed transform
=> Change Jenkins transform step

download.yaml, kg_covid_19/transform.py, kg_covid_19/transform_utils/gocam_transform/__init__.py, kg_covid_19/transform_utils/gocam_transform/gocam_transform.py, kg_covid_19/transform_utils/ontology/ontology_transform.py, kg_covid_19/utils/transform_utils.py, merge.yaml, tests/test_download.py, tests/test_download_from_yaml.py, tests/test_run.py
WIP - this ingests go-cam models produced by @callahantiff and Bill, to address #153 
@deepakunni3, please feel free to close this PR if you'd rather do it some other way. 
Currently doesn't produce any useful edges
=> First pass at go-cam ingest

Jenkinsfile
Added line in Jenkinsfile to make and upload list of all YAML manifest files
=> Add list of all YAML manifest files

Jenkinsfile, kg_covid_19/utils/download_utils.py, setup.py
Seems to be causing some issues in our Jenkins pipeline indirectly, because of its llvmlite dependency
=> Remove encodeproject dependency

kg_covid_19/merge_utils/merge_kg.py, merge.yaml, requirements.txt, run.py, tests/resources/merge_MISSING_FILE.yaml, tests/resources/merge_valid.yaml
This PR,
- modifies the merge step to use KGX's merge operation
- exposes `processes` argument for the merge step: `python run.py merge -p 8`
- updates the merge.yaml configuration
- updates requirements.txt to pin KGX to `kg-covid-19` branch
=> Update merge step by leveraging KGX

download.yaml, kg_covid_19/merge_utils/merge_kg.py, merge.yaml, requirements.txt, run.py, tests/resources/merge_MISSING_FILE.yaml, tests/resources/merge_valid.yaml
To address this reviewer comment:
https://docs.google.com/document/d/1Hk5pdv34NgfKuX4JitwYLPc-bF_ztnpGuMWrqJsVJt0/edit?disco=AAAAKPZTcYk
=> Added note to download.yaml to instruct users about how to download from S3 buckets

kg_covid_19/transform_utils/scibite_cord/scibite_cord.py
to address reviewers comment asking for better progress indicators
=> Add progress indicators/message to scibite ingest

.github/ISSUE_TEMPLATE/dataset-request.md
separated out URL field
added "benefit" field
=> enhanced issue template

kg_covid_19/utils/download_utils.py
Need to set agent for some downloads
=> Fix download bug

Jenkinsfile
This required a slightly hacky command
=> Added existing builds in index.html for project dir

kg_covid_19/transform_utils/chembl/chembl_transform.py
- Remaps ChEMBL Target node for SARS-CoV-2 to the actual NCBITaxon.
- Also fixes a bug in the generated nodes and edges TSV where the columns were being duplicated.
renamed branch `fix-chembl-organism` to `fix-chembl-organism_run_jenkins` to trigger Jenkins build, closing #367 in favor of this PR
thanks @deepakunni3
=> Remap Chembl target to NCBITaxon for SARS-CoV-2

kg_covid_19/merge_utils/merge_kg.py, kg_covid_19/transform_utils/sars_cov_2_gene_annot/sars_cov_2_gene_annot.py
(category for some nodes was not be set properly)
=> Fix bug in sars-cov-2-gene_annot ingest 

queries/sparql/query-07-drug-to-drug-target.rq
Adding sparql query for drug -> drug targets per convo with @callahantiff 
@matentzn could you have a look at this sparql query and 1) confirm it's okay and 2) maybe give some advice about why it's timing out? It should return at most 30k things, so it doesn't seem too demanding
=> Add query for drug -> drug targets

merge.yaml, merge_jenkins.yaml
Fix call to kgx.graph_operations.summarize_graph.generate_graph_stats in merge*.yaml
(was kgx.operations.summarize_graph.generate_graph_stats)
=> Fix call to kgx.graph_operations.summarize_graph.generate_graph_stats

Jenkinsfile
(otherwise we try to write to /.ansible)
=> Fix call to ansible-playbook by setting home directory to pwd

Jenkinsfile, requirements.txt, setup.py
This should fix [this issue](https://github.com/biolink/kgx/issues/330), [this issue](https://github.com/biolink/kgx/issues/329)
=> Move KGX pin to 1.5.1

download.yaml
Updating URLs for DrugCentral and TCRD data.
=> Update URLs in download.yaml
