kg_emerging_viruses/transform_utils/drug_central/drug_central.py, kg_emerging_viruses/utils/transform_utils.py
- several lines contain only drug info, no target info, example:
```
"phenylbutanoic acid"   24      "glutamine"     "Amino acid"                                                    "Mechanism of Action"   "DRUG LABEL"            1       "DRUG LABEL"            "http://www.accessdata.fda.gov/drugsatfda_docs/label/2009/020572s016,020573s015lbl.pdf" "OTHER"
```
skipping these lines
=> Fix problem parsing drug central

kg_covid_19/transform.py, kg_covid_19/transform_utils/drug_central/drug_central.py, kg_covid_19/transform_utils/hpo/hpo.py, kg_covid_19/transform_utils/string_ppi/string_ppi.py, kg_covid_19/transform_utils/transform.py, kg_covid_19/transform_utils/ttd/ttd.py, kg_covid_19/transform_utils/zhou_host_proteins/zhou_transform.py, run.py
This PR address #59 and also allows for configurable transform.
This is useful when we want to run just handful of sources instead of all of them.
To run your transforms,
```
python run.py download -s HpoTransform -s TTDTransform
```
If nothing is provided then it runs all the transforms as defined in `kg_covid_19/transform.py`.
=> Configurable transform and proper handling of input and output directory

README.rst, setup.py
- added a few deps to `setup.py`
- added an item in `README.rst` to run `pip install -r requirements.txt` (to ensure KGX is installed)
=> Update readme and setup

download.yaml
=> Update URL for Scibite download to last known working version, at BBOP

kg_covid_19/transform_utils/zhou_host_proteins/zhou_transform.py
partially addresses #86 
> zhou_host_proteins
> biotically interacts with should be replaced with biolink:interacts_with
> Genes with prefix NCBI should be replaced with the prefix NCBIGene
=> Fix biolink terms and gene CURIE prefix Zhou et al data transform

kg_covid_19/load_utils/merge_kg.py, tests/resources/merge_MISSING_FILE.yaml, tests/resources/merge_valid.yaml, tests/test_run.py
- Added code/test for raising FileNotFound if file is specified in merge yaml but doesn't exist
- Also fixed a skipped test for checking run.py transform exits when given a -i parameters that doesn't exist
=> Added code/tests to check for missing files before performing merge

kg_covid_19/transform_utils/drug_central/drug_central.py, kg_covid_19/transform_utils/intact/intact.py, kg_covid_19/transform_utils/pharmgkb/pharmgkb.py, kg_covid_19/transform_utils/sars_cov_2_gene_annot/sars_cov_2_gene_annot.py, kg_covid_19/transform_utils/transform.py, kg_covid_19/transform_utils/ttd/ttd.py, kg_covid_19/transform_utils/zhou_host_proteins/zhou_transform.py, tests/test_intact.py, tests/test_sars_cov_2_gene_annot.py, tests/test_transform_class.py
Add provided by edges to several ingests, to address #121
=> Add provided by to edges

kg_covid_19/load_utils/merge_kg.py, merge.yaml
Now you can run,
```
python run.py load
```
You can create more than one artifact from the merged graph.
This behavior is driven by `merge.yaml`.
To export to Neo4j, uncomment the lines in `merge.yaml`
=> Update load_and_merge operation to support more than one destination 

Jenkinsfile
- wrap stages in dir('gitrepo') instead of repeatedly doing `cd gitrepo`
- upload output of transform() to s3
- fix logic in download() that prevents proper fxn in non-master branch
=> Improvements to Jenkinsfile

download.yaml, kg_covid_19/transform_utils/scibite_cord/scibite_cord.py
This PR bumps up the version of SciBite CORD-19 datasets in `download.yaml`
@justaddcoffee I added back the entity co-occurrence dataset but its not being transformed at the moment. If we transform that dataset, we end up with ~23 million nodes and ~23 million edges just from this ingest. 
Maybe we can enable the transformation later on, if needed.
=> Update scibite cord ingest

kg_covid_19/load_utils/merge_kg.py
This PR adds the ability to create graph stats for each sub-graph and the final merged graph.
It's still using KGX under the hood. Please be sure to use `kg-covid-19` branch of KGX.
=> Generate summary stats for graphs at the time of merge

Jenkinsfile
- upload stats to s3
- fix a few logical bugs
=> Jenkins upload stats fix bugs

Jenkinsfile
=> Push transformed data during publish stage in Jenkins

README.rst
Added more prominent link to Wiki, and moved installating/usage advice there
closes #202
=> Added more prominent link to Wiki, and move installation/usage advice there

kg_covid_19/utils/transform_utils.py, tests/test_transform_utils.py
This should address #201 (at least in part)
=> Replace internal tabs in data to be written out as TSVs

kg_covid_19/transform_utils/sars_cov_2_gene_annot/sars_cov_2_gene_annot.py, tests/test_sars_cov_2_gene_annot.py
@deepakunni3 per our convo this afternoon, I've changed the nodes we are emitting in the SARS-CoV-2 such that taxon info is in this column:
`in_taxon`
and the rows in this column are ncbi taxon CURIEs that look like this:
`NCBITaxon:2697049`
=> Prettify taxon id in sars-cov-2 gene annotations

kg_covid_19/transform_utils/sars_cov_2_gene_annot/sars_cov_2_gene_annot.py, kg_covid_19/utils/transform_utils.py, tests/test_sars_cov_2_gene_annot.py
`name` in nodes.tsv is now the symbol from GPI, `full_name` is the name from GPI
also fixed a bug in `synonyms` that was emitting just the first character of the synonyms
=> Fix names and symbols for SARS-CoV-2 gene annotation ingest

kg_covid_19/merge_utils/merge_kg.py, merge.yaml, requirements.txt
Update merge logic to support filters and operations.
This PR adds support for,
- filtering graphs at the time of merge (currently supports filters for TSVs, and Neo4j)
- applying operations to graphs (like ID remapping)
Filters are applied **before** the graph is loaded.
Operations are applied **after** the graph is loaded.
`merge.yaml` provides a good example of using filters and operations for STRING.
This can be applied to any source.
**Note:** This PR depends on switching KGX to `master`.
=> Update merge script to support filters

kg_covid_19/transform.py, kg_covid_19/transform_utils/chembl/__init__.py, kg_covid_19/transform_utils/chembl/chembl_activity_query.json, kg_covid_19/transform_utils/chembl/chembl_assay_query.json, kg_covid_19/transform_utils/chembl/chembl_document_query.json, kg_covid_19/transform_utils/chembl/chembl_molecule_query.json, kg_covid_19/transform_utils/chembl/chembl_transform.py, merge.yaml
ChEMBL ingest for SARS-CoV-2 subset.
The nature of the subset is described here: http://chembl.blogspot.com/2020/05/chembl27-sars-cov-2-release.html
The code basically queries different ChEMBL resources and fetches the relevant data.
We can expand on this with additional canned queries that be used to fetch more defined subsets.
=> ChEMBL ingest for SARS-CoV-2 subset

curated/ORFs/uniprot_sars-cov-2.gpi, download.yaml, kg_covid_19/transform_utils/scibite_cord/scibite_cord.py
@cmungall @deepakunni3 this PR bumps up Scibite ingest to their version 1.5, to address #261. 
Note that they now split the file that we ingest into two files, and also that they've eliminated the directories that we are using to infer the 'subset' of the corpus (Biorxiv, etc). So, I've refactored accordingly.
=> Update scibite annotation version to 1.5

kg_covid_19/merge_utils/merge_kg.py
Just a one line fix to ensure that we generate counts by `provided_by` for the summary statistics YAML.
=> Fix stats generation to include counts for 'provided_by' property

kg_covid_19/transform_utils/string_ppi/node_header.json, kg_covid_19/transform_utils/string_ppi/string_ppi.py, tests/test_string.py
We use both `alias` and `xrefs` in STRING. 
`alias` was chosen back in March but `xrefs` is more semantically appropriate.
=> Combine alias and xrefs for STRING

kg_covid_19/transform_utils/chembl/chembl_transform.py
Remap `synonyms` column to `synonym`.
The latter is the appropriate biolink model property.
=> Remap synonyms to synonym property in ChemblTransform

queries/sparql/query-04-sars-cov-2-interactors_2nd_order.yaml, run.py
also fixed a bug causing crash when output dir doesn't exist
=> Update 2nd order interact query

kg_covid_19/merge_utils/merge_kg.py, kg_covid_19/transform_utils/chembl/chembl_transform.py, kg_covid_19/transform_utils/drug_central/drug_central.py, kg_covid_19/transform_utils/intact/intact.py, kg_covid_19/transform_utils/pharmgkb/pharmgkb.py, kg_covid_19/transform_utils/sars_cov_2_gene_annot/sars_cov_2_gene_annot.py, kg_covid_19/transform_utils/scibite_cord/scibite_cord.py, kg_covid_19/transform_utils/string_ppi/edge_core_header.json, kg_covid_19/transform_utils/string_ppi/string_ppi.py, kg_covid_19/transform_utils/ttd/ttd.py, kg_covid_19/transform_utils/zhou_host_proteins/zhou_transform.py, tests/test_drug_central.py, tests/test_intact.py, tests/test_sars_cov_2_gene_annot.py, tests/test_string.py
This PR,
- types edges as `biolink:Association`. This is now required by KGX to reify an edge when exporting as RDF
- also specifies the type for certain properties. This ensure that the value of these properties are treated properly when exporting RDF
=> Type edges as associations

Jenkinsfile
- Added missing -c arg to s3cmd ls
- fixed bug preventing timestamped YAML files from being push to s3
=> Fixed upload of YAML manifests in Jenkins

Jenkinsfile
To address #135 and also MS reviewers' request that we provide versioning for our builds
This PR:
- writes out all files for a build to a timestamped directory eg. 20201231 (including 
- merged graph in TSV format
- an RDF version of the merged graph
- the `raw/` directory with the data ingested to make build
- the `transformed/` directory containing subgraphs
- a `stats` directory with statistics about the build
- the `Jenkinsfile` containing that actually ran the build
- copies this directory to a current/ directory so users can have a URL to retrieve the most current build
- also adds index.html files to each of the directories mentioned above, to allow browsing/listing of contents for directories
=> Add versioning of builds to Jenkinsfile

setup.py
Updated ensmallen_graph causes a panic in 
` TestEdges.test_make_edges_pos_train_test_valid_edges_distinct_1_neg_train_edges_tsv`:
```
neg_train_edges, neg_test_edges = \
>           all_negative_edges.random_holdout(seed=seed, train_percentage=train_fraction)
E       pyo3_runtime.PanicException: index out of bounds: the len is 0 but the index is 53
```
Pinned to 0.3.6 for now
=> pin ensmallen_graph to 0.3.6 for now to pass tests

Jenkinsfile, merge.yaml, merge_jenkins.yaml
Slight change such that nt/rdf is not produced from `run.py merge` by default, but only in Jenkins pipeline
=> Produce nt only in jenkins

kg_covid_19/transform_utils/scibite_cord/scibite_cord.py
Refactor Scibite ingest slightly so that unzipped files are removed from `data/raw` after processing. 
Currently `raw` is being uploaded to S3 for each of our builds, and it's taking >1.5h, I think in part because of these unzipped files, see [here](https://build.berkeleybop.io/job/knowledge-graph-hub/job/kg-covid-19/job/master/151/execution/node/135/log/)
=> Removed unzipped files from `data/raw` after processing in Scibite ingest

Jenkinsfile
index.html is clobbered on s3 for existing builds - this fixes that
Also fails early if there is a problem pip installing things during publish
=> Fix index.html for existing builds

kg_covid_19/make_holdouts.py, setup.py
Update calls to ensmallen_graph to use new bindings correctly. This should address #349 too. 
We'll need to wait until ensmallen_graph version 0.4.3 is published before running Jenkins and testing whether this works. Until then this draft PR will fail.
=> Update code to use new ensmallen_graph bindings correctly

requirements.txt
Fixes a [build issue](https://build.berkeleybop.io/job/knowledge-graph-hub/job/kg-covid-19/job/master/171/console) seemingly caused by problematic pyshex version 0.7.15 - I'm pinning this to 0.7.14 for now
```
18:54:45  + python3.7 run.py transform
18:54:46  /var/lib/jenkins/workspace/dge-graph-hub_kg-covid-19_master/gitrepo/venv/lib/python3.7/site-packages/biolinkml/__init__.py:158: UserWarning: Some URL processing will fail with python 3.7.5 or earlier.  Current version: sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
18:54:46    warn(f"Some URL processing will fail with python 3.7.5 or earlier.  Current version: {sys.version_info}")
18:54:46  Traceback (most recent call last):
18:54:46    File "run.py", line 6, in <module>
18:54:46      from kg_covid_19 …
```
=> Fix pyshex issue run jenkins

queries/query-02-sars-cov-2-prot.rq, queries/query-03-sars-cov-2-interactors.rq, queries/query-04-sars-cov-2-interactors_2nd_order.rq, queries/query-05-sars-cov-2-interactors_druggable_2nd_order.rq, queries/query-06-provided_by_counts.rq, queries/query-07-drug-to-drug-target.rq
Related to the previous pull request to fix grlc API SPARQL queries: https://github.com/Knowledge-Graph-Hub/kg-covid-19/pull/396#issuecomment-780754210
Added missing `:` in the grlc metadata and replaced `title` by `summary`
=> Fix SPARQL queries metadata for grlc API

merge_jenkins.yaml
This block was missing from `merge_jenkins.yaml`:
```
chebi:
type: tsv
filename:
- data/transformed/ontologies/chebi_nodes.tsv
- data/transformed/ontologies/chebi_edges.tsv
```
So chebi wasn't actually making it into the merged graph. This PR fixes that
=> Add Chebi to merged graph

kg_covid_19/transform_utils/scibite_cord/scibite_cord.py
Per Monarch data discussion, instead of this edge:
` [some science thing] biolink:related_to CORD:paper`
make this edge:
`CORD:paper biolink:mentions [some science thing]`
=> Refine scibite biolink edge type

Jenkinsfile
It's evident that previous runs in a given workspace are causing some issues here:
- download stages are clearly using existing data from previous runs instead of download fresh data
- blazegraph journal file from previous runs still exist, causing unexpected behavior (pigz dies with unhelpful message caused by it wanting to talk to an interactive terminal to ask whether it should overwrite existing file)
- git repo from previous run still exists, causing git clone to fail
Adding cleanWs() to the post stage should fix this
=> Add cleanws to post stage in Jenkinsfile

Jenkinsfile
Seeing if it breaks at blazegraph publish stage.
=> Remove previous SSH config for pan

Jenkinsfile
Pushing to public Blazegraph was failing with 
```
Failed to connect to the host via ssh: Host key verification failed.
```
This adds the ssh-keyscan call back in to retrieve SSH host keys.
=> Re-add ssh-keyscan

Jenkinsfile
This index refresh is handled by other scripts now.
=> Remove the top-level HTML index refresh in Jenkinsfile
